[package]
name = "ckb-pcn-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive", "env", "string"] }
clap-serde-derive = "0.2.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
lightning = { version = "0.0.121", features = ["max_level_trace"] }
lightning-block-sync = { version = "0.0.121", features = [
    "rpc-client",
    "tokio",
] }
lightning-invoice = { version = "0.29.0" }
lightning-net-tokio = { version = "0.0.121" }
lightning-persister = { version = "0.0.121" }
lightning-background-processor = { version = "0.0.121", features = ["futures"] }
lightning-rapid-gossip-sync = { version = "0.0.121" }
base64 = "0.13.0"
bitcoin = { version = "0.30.2", features = ["serde", "rand"] }
bitcoin-bech32 = "0.12"
bech32 = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
rand = "0.8.5"
serde_json = { version = "1.0" }
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "net",
    "time",
    "signal",
] }
home = "0.5.9"
ckb-sdk = "3.1.0"
thiserror = "1.0.58"
anyhow = "1.0.81"
env_logger = "0.11.3"
tentacle = { git = "https://github.com/nervosnetwork/tentacle", branch = "bump-to-0.6.0" }
log = "0.4.21"
futures = "0.3.30"
once_cell = "1.19.0"
tokio-util = { version = "0.7.10", features = ["rt"] }
molecule = { version = "0.7.5", default-features = false }
ckb-types = "0.114.0"
ckb-jsonrpc-types = "0.114.0"
ckb-crypto = "0.114.0"
rocksdb = { package = "ckb-rocksdb", version ="=0.21.1", features = ["snappy"], default-features = false }
serde_with = { version = "3.7.0", features = ["macros", "base64"] }
hex = "0.4.3"
tower = "0.4.13"
axum = { version = "0.7.5", features = ["json"] }
bitflags = { version = "2.5.0", features = ["serde"] }
ckb-hash = "0.115.0"
secp256k1 = { version = "0.28.0", features = ["serde", "recovery"] }
musig2 = { version = "0.0.11", features = ["secp256k1", "serde"] }
ractor = "0.9.7"
arcode = "0.2.4"
nom = "7.1.3"
ckb-testtool = { git = "https://github.com/contrun/capsule.git", branch = "determinisitic-rng" }

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dev-dependencies]
tempfile = "3.10.1"
